name: Pipeline CI/CD
#Define quando o pipeline é disparado
on: 
  push:
    branches:
        - main
    paths: #Só dispara quando os arquivos dessas pastas mudarem
      - "src/**"
      - ".github/workflows/**"
  workflow_dispatch: #Habilitar o botão "Run Workflow" no Github Actions


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"
          cache-dependency-path: package-lock.json
      
      - name: Instalação das dependências
        run: npm install 

      - name: Rodar o build
        run: npm run build
       
  tests:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"
          cache-dependency-path: package-lock.json
      
      - name: Instalação das dependências
        run: npm install 

      - name: Rodar Lint
        run: npm run lint
      
      - name: Rodar Formatação
        run: npm run format

      - name: Rodar testes
        run: npm run test
  
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"
          cache-dependency-path: package-lock.json
      
      - name: Instalação Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy Vercel
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            
